//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncController.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empnormal
    {
        public string eno { get; set; }
        public string dept { get; set; }
        public string prjcode { get; set; }
        public Nullable<int> Hours { get; set; }
    }
}
