//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst_EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sravyaEntities : DbContext
    {
        public sravyaEntities()
            : base("name=sravyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<empnormal> empnormals { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<vwEmpbyDept> vwEmpbyDepts { get; set; }
    
        public virtual int payslip_generation(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("payslip_generation", empidParameter);
        }
    
        public virtual int sp_getavgsal_empcount(Nullable<int> did, ObjectParameter avgsal)
        {
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getavgsal_empcount", didParameter, avgsal);
        }
    }
}
