//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Async_Controllers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Cancellations = new HashSet<Cancellation>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TrainNo { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> DateOfJourney { get; set; }
        public Nullable<int> SeatsBooked { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string CustomerName { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Train Train { get; set; }
    }
}
