//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asynchronous_Controllers_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int CancellationID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<int> SeatsCancelled { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
