//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asynchronous_Controllers_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int empno { get; set; }
        public string ename { get; set; }
        public string job { get; set; }
        public Nullable<int> mgr_id { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> comm { get; set; }
        public Nullable<int> deptno { get; set; }
    
        public virtual dept dept { get; set; }
    }
}
