//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asynchronous_Controllers_Prj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQL_Assignment1Entities : DbContext
    {
        public SQL_Assignment1Entities()
            : base("name=SQL_Assignment1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cancellation> Cancellations { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<dept> depts { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmpProjectTask> EmpProjectTasks { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
